<?php

$this->device_types['ledlamp'] = array(
    'TITLE'=>'LedLamp',
    'PARENT_CLASS'=>'SControllers',
    'CLASS'=>'SLedLamp',
    'DESCRIPTION'=>'LedLamp @gunner47',
    'PROPERTIES'=>array( 
        'state'=>array('DESCRIPTION'=>'MQTT state', 'ONCHANGE'=>'stateUpdated'),
        'cmnd'=>array('DESCRIPTION'=>'MQTT command'),
        'effect'=>array('DESCRIPTION'=>'Effect','_CONFIG_TYPE'=>'select','_CONFIG_OPTIONS'=>'0=White color,1=Color,2=Colors,3=Madness,4=Clouds,5=Lava,6=Plasma,7=Rainbow 3D,8=Rainbow stripe,9=Zebra,10=Forest,11=Ocean,12=Balls,13=Balls bounce,14=Popcorn,15=Spiro,16=Prismata,17=Smoke balls,18=Pacific,19=Shadows,20=DNA,21=Flock,22=Flock and predator,23=Butterfys,24=Butterflys lamp,25=Snakes,26=Nexus,27=Spheres,28=Sinusoid,29=Metaballs,30=Aurora,31=Spider,32=Lava lamp,33=Liquid lamp,34=Liquid lamp (auto),35=Drops,36=Matrix,37=Fire 2012,38=Fire 2018,39=Fire 2020,40=Fire,41=Whirl,42=Whirl multi,43=Magma,44=Boil,45=Waterfall,46=Waterfall 4 in 1,47=Pool,48=Pulse,49=Pulse rainbow,50=Pulse white,51=Oscillating,52=Fountain,53=Fairy,54=Comet,55=Comet color,56=Comet two,57=Comet three,58=Attract,59=Firefly,60=Firefly top,61=Snake,62=Sparkles,63=Twinkles,64=Smoke,65=Smoke color,66=Picasso,67=Picasso2,68=Picasso3,69=Waves,70=Sand,71=Rings,72=Cube2D,73=Simple rain,74=Stormy rain,75=Color rain,76=Rain,77=Show,78=Starfall,79=Leapers,80=Lighters,81=Lighters traces,82=Paintball,83=Rainbow,84=Clock,85=Text', 'ONCHANGE'=>'paramsUpdated'),
        'brightness'=>array('DESCRIPTION'=>'Brightness (%)','_CONFIG_TYPE'=>'num', 'ONCHANGE'=>'paramsUpdated','DATA_KEY'=>1),
        'speed'=>array('DESCRIPTION'=>'Speed','_CONFIG_TYPE'=>'num', 'ONCHANGE'=>'paramsUpdated'),
        'scale'=>array('DESCRIPTION'=>'Scale','_CONFIG_TYPE'=>'num', 'ONCHANGE'=>'paramsUpdated'),
        'color'=>array('DESCRIPTION'=>'Color (effect Color)','_CONFIG_TYPE'=>'rgb','ONCHANGE'=>'colorUpdated','DATA_KEY'=>1),
        'timer_work'=>array('DESCRIPTION'=>'Timer work'),
        'timer_state'=>array('DESCRIPTION'=>'Timer state','_CONFIG_TYPE'=>'select','_CONFIG_OPTIONS'=>'1=Off,2=1 min,3=5 min,4=10 min,5=15 min,6=30 min,7=45 min,8=60 min', 'ONCHANGE'=>'paramsUpdated'),
        'button_lock'=>array('DESCRIPTION'=>'Button locked','_CONFIG_TYPE'=>'yesno', 'ONCHANGE'=>'paramsUpdated'),
        'almset_1'=>array('DESCRIPTION'=>'Alarm 1 set','_CONFIG_TYPE'=>'yesno', 'ONCHANGE'=>'paramsUpdated'),
        'almtime_1'=>array('DESCRIPTION'=>'Alarm 1 time (hh:mm)','_CONFIG_TYPE'=>'text', 'ONCHANGE'=>'paramsUpdated'),
        'almset_2'=>array('DESCRIPTION'=>'Alarm 2 set','_CONFIG_TYPE'=>'yesno', 'ONCHANGE'=>'paramsUpdated'),
        'almtime_2'=>array('DESCRIPTION'=>'Alarm 2 time (hh:mm)','_CONFIG_TYPE'=>'text', 'ONCHANGE'=>'paramsUpdated'),
        'almset_3'=>array('DESCRIPTION'=>'Alarm 3 set','_CONFIG_TYPE'=>'yesno', 'ONCHANGE'=>'paramsUpdated'),
        'almtime_3'=>array('DESCRIPTION'=>'Alarm 3 time (hh:mm)','_CONFIG_TYPE'=>'text', 'ONCHANGE'=>'paramsUpdated'),
        'almset_4'=>array('DESCRIPTION'=>'Alarm 4 set','_CONFIG_TYPE'=>'yesno', 'ONCHANGE'=>'paramsUpdated'),
        'almtime_4'=>array('DESCRIPTION'=>'Alarm 4 time (hh:mm)','_CONFIG_TYPE'=>'text', 'ONCHANGE'=>'paramsUpdated'),
        'almset_5'=>array('DESCRIPTION'=>'Alarm 5 set','_CONFIG_TYPE'=>'yesno', 'ONCHANGE'=>'paramsUpdated'),
        'almtime_5'=>array('DESCRIPTION'=>'Alarm 5 time (hh:mm)','_CONFIG_TYPE'=>'text', 'ONCHANGE'=>'paramsUpdated'),
        'almset_6'=>array('DESCRIPTION'=>'Alarm 6 set','_CONFIG_TYPE'=>'yesno', 'ONCHANGE'=>'paramsUpdated'),
        'almtime_6'=>array('DESCRIPTION'=>'Alarm 6 time (hh:mm)','_CONFIG_TYPE'=>'text', 'ONCHANGE'=>'paramsUpdated'),
        'almset_7'=>array('DESCRIPTION'=>'Alarm 7 set','_CONFIG_TYPE'=>'yesno', 'ONCHANGE'=>'paramsUpdated'),
        'almtime_7'=>array('DESCRIPTION'=>'Alarm 7 time (hh:mm)','_CONFIG_TYPE'=>'text', 'ONCHANGE'=>'paramsUpdated'),
        'dawn_state'=>array('DESCRIPTION'=>'Dawn option','_CONFIG_TYPE'=>'select','_CONFIG_OPTIONS'=>'1=1 min,2=5 min,3=10 min,4=15 min,5=30 min,6=45 min,7=60 min', 'ONCHANGE'=>'paramsUpdated'),
    ),
    'METHODS'=>array(
        'stateUpdated'=>array('DESCRIPTION'=>'MQTT state updated event'), 
        'paramsUpdated'=>array('DESCRIPTION'=>'Params updated event'), 
        'colorUpdated'=>array('DESCRIPTION'=>'Color updated event'), 
        'switch'=>array('DESCRIPTION'=>'Switch'),
        'turnOn'=>array('DESCRIPTION'=>LANG_DEVICES_TURN_ON,'_CONFIG_SHOW'=>1),
        'turnOff'=>array('DESCRIPTION'=>LANG_DEVICES_TURN_OFF,'_CONFIG_SHOW'=>1), 
        'statusUpdated'=>array('DESCRIPTION'=>'Status updated','CALL_PARENT'=>1), 
    ),
);
